---
site_name: Zarhus - Your Digital Chess Knight
site_url: https://docs.zarhus.com

repo_url: https://github.com/zarhus/docs
edit_uri: blob/main/docs/
theme:
  name: material
  # custom_dir: overrides
  favicon: images/favicon.png
  logo: images/zarhus-logo-white.png
  features:
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
extra:
  analytics:
    provider: google
    property: TBD
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zarhus
      # - icon: fontawesome/brands/mastodon
      #   link: https://fosstodon.org/@TBD
      # - icon: fontawesome/brands/twitter
      #   link: https://twitter.com/TBD
      # - icon: fontawesome/brands/reddit
      #   link: https://www.reddit.com/r/TBD
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.superfences
  - attr_list
  - meta
  - md_in_html
  - toc:
      toc_depth: 3
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

plugins:
  - search
  - macros
  - mkdocs-video

nav:
  - 'Intro':
      - 'About Zarhus': index.md
      - 'New? Start here': newcomers.md
  - 'Getting started':
      - 'Building': getting-started/building.md
      - 'Flashing': getting-started/flashing.md
      - 'Verification': getting-started/verification.md
  - 'Supported targets':
      - 'Targets': supported-targets/targets.md
      - 'Radxa':
          - 'Radxa CM3': supported-targets/radxa-cm3.md
      - 'Raspberry Pi':
          - 'Raspberry Pi 4': supported-targets/rpi4.md
      - 'PINE64':
          - 'Quartz64 Model A': supported-targets/quartz64-a.md
  - 'Guides':
      - 'Managing packages': guides/managing-packages.md
      - 'Managing layers': guides/managing-layers.md
      - 'Secure Boot Verification': guides/secure-boot/secure-boot-verification.md
      - 'Zarhus OS on CROSSCON Hypervisor on RPi 4': guides/rpi4-crosscon-hypervisor.md
  - 'Development Process':
      - 'Standard Release Process': development-process/standard-release-process.md
  - 'FAQ': faq.md
