---
site_name: Zarhus - Your Digital Chess Knight
site_url: https://docs.zarhus.com

repo_url: https://github.com/zarhus/docs
theme:
  name: material
  #custom_dir: overrides
  favicon: images/favicon.png
  logo: images/zarhus-logo-white.png
  features:
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
extra:
  analytics:
    provider: google
    property: TBD
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zarhus
    #- icon: fontawesome/brands/mastodon
    #  link: https://fosstodon.org/@TBD
    #- icon: fontawesome/brands/twitter
    #  link: https://twitter.com/TBD
    #- icon: fontawesome/brands/reddit
    #  link: https://www.reddit.com/r/TBD
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.superfences
  - attr_list
  - meta
  - md_in_html
  - toc:
      toc_depth: 2
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

plugins:
  - search
  - mkdocs-video

nav:
  - 'Intro':
      - 'About Zarhus': index.md
      - 'New? Start here': newcomers.md
  - 'Base OS':
    - 'Building': base-os/building.md
    - 'Flashing': base-os/flashing.md
  - 'Guides':
    - 'Managing packages': guides/managing-packages.md
    - 'Managing layers': guides/managing-layers.md
  - 'FAQ': faq.md
